// <auto-generated />
using System;

namespace ModInteropImportGenerator;

/// <summary>
///   Generate ModInterop fields based on the method names and signatures.
/// </summary>
/// <param name="modInteropName">
///   The export name, sourced from the exporting mod's ModExportNameAttribute.
/// </param>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public class GenerateImportsAttribute(string modInteropName) : Attribute
{
    public string ModInteropName { get; } = modInteropName;

    public bool RequiredDependency { get; set; } = false;
}
