using System;
using System.Collections.Generic;
using ModInteropImportGenerator.Sample.Stubs;

namespace ModInteropImportGenerator.Sample;

[GenerateImports("FrostHelper", RequiredDependency = false)]
public static partial class FrostHelper
{
    /// <summary>
    /// Creates an object which can evaluate a Session Expression.
    /// The returned object can be passed to GetSessionExpressionValue and other similar methods.
    /// Refer to https://github.com/JaThePlayer/FrostHelper/wiki/Session-Expressions
    /// </summary>
    public static partial bool TryCreateSessionExpression(string str, out object expression);

    /// <summary>
    /// Creates an object which can evaluate a Session Expression, using the given Session Expression Context.
    /// The context object should be generated by <see cref="CreateSessionExpressionContext"/>.
    /// The returned object can be passed to GetSessionExpressionValue and other similar methods.
    /// Refer to https://github.com/JaThePlayer/FrostHelper/wiki/Session-Expressions
    /// </summary>
    public static partial bool TryCreateSessionExpression(string str, object context, out object expression);

    /// <summary>
    /// Returns the current value of a Session Expression.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static partial object GetSessionExpressionValue(object expression, SessionStub session);

    /// <summary>
    /// Returns the current value of a Session Expression with the given userdata, which can be any arbitrary object,
    /// passed to custom commands defined by the Session Expression Context used when creating the Session Expression.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static partial object GetSessionExpressionValue(object expression, SessionStub session, object userdata);

    /// <summary>
    /// Returns the type that the given session expression will return, or typeof(object) if that's unknown.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static partial Type GetSessionExpressionReturnedType(object expression);

    /// <summary>
    /// Returns the current value of a Session Expression as an integer, coercing it if needed.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static partial int GetIntSessionExpressionValue(object expression, SessionStub session);
    public static partial int GetIntSessionExpressionValue(object expression, SessionStub session, object userdata);

    /// <summary>
    /// Returns the current value of a Session Expression as a float, coercing it if needed.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static partial float GetFloatSessionExpressionValue(object expression, SessionStub session);
    public static partial float GetFloatSessionExpressionValue(object expression, SessionStub session, object userdata);

    /// <summary>
    /// Returns the current value of a Session Expression as a boolean, coercing it if needed.
    /// The object passed as the 1st argument needs to be created via <see cref="TryCreateSessionExpression(string, object, out object?)"/>
    /// </summary>
    public static partial bool GetBoolSessionExpressionValue(object expression, SessionStub session);
    public static partial bool GetBoolSessionExpressionValue(object expression, SessionStub session, object userdata);

    /// <summary>
    /// Registers a simple Session Expression command, which will be accessible via $modName.cmdName in Session Expressions.
    /// </summary>
    /// <param name="modName">Name of the mod which registers this command. Will be used to prefix the command name.</param>
    /// <param name="cmdName">Name of the command</param>
    /// <param name="func">Function called each time the command needs to be evaluated</param>
    public static partial void RegisterSimpleSessionExpressionCommand(string modName, string cmdName, Func<SessionStub, object> func);

    /// <summary>
    /// Registers a Session Expression function, which will be accessible via $modName.cmdName in Session Expressions.
    /// </summary>
    /// <param name="modName">Name of the mod which registers this command. Will be used to prefix the command name.</param>
    /// <param name="cmdName">Name of the command</param>
    /// <param name="func">Function called each time the function needs to be evaluated.
    /// 2nd argument contains a list of the values of all arguments to the function.
    /// </param>
    public static partial void RegisterFunctionSessionExpressionCommand(string modName, string cmdName, Func<SessionStub, IReadOnlyList<object>, object> func);

    /// <summary>
    /// Creates a Session Expression Context object, which can be passed to <see cref="TryCreateSessionExpression(string,object,out object?)"/>
    /// This allows you to register custom commands for specific entities.
    /// A context should be created once, and reused as much as possible.
    /// <br />
    /// Do not capture entity instances into the Func objects, instead pass a `userdata` object when calling GetSessionExpressionValue,
    /// which will be passed as the 2nd argument your functions.
    /// <br />
    /// Dictionary keys are names under which the commands will be available. For example, if your key is 'coolValue',
    /// then it will be accessed as `$coolValue` in Session Expressions created using this context.
    /// </summary>
    public static partial object CreateSessionExpressionContext(
        Dictionary<string, Func<SessionStub, object /* userdata */, object>> simpleCommands,
        Dictionary<string, Func<SessionStub, object /* userdata */, IReadOnlyList<object>, object>> functionCommands);
}
